baseURL = "https://concretepump.bangunan.co/"
languageCode = "id"
title = "Sewa Concrete Pump | Sewa Concrete Pump, Pompa Beton, Belalai Harian & Bulanan Murah"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Tempat Sewa Concrete Pump - Solusi sewa concrete pump dengan harga terjangkau, tersedia untuk kebutuhan harian dan bulanan. Pompa beton untuk membantu mempercepat proyek pengecoran efisien dan hemat"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["sewa concrete pump", "pompa beton murah", "sewa pompa beton", "sewa pompa beton harian", "sewa pompa beton bulanan", "concrete pump cor"]
  base_price = 3000000
  price_range = 1000000
  free_consultation = true
  service_types = [
  "Sewa Concrete Pump Harian",
  "Sewa Concrete Pump Bulanan",
  "Sewa Pompa Beton Long Boom",
  "Sewa Pompa Beton Mini",
  "Sewa Pompa Beton Master Long Boom"
  ]
  categories = ["Sewa Concrete Pump", "Pompa Beton Cor", "Sewa Alat Cor"]
  payment_methods = ["Bayar Bertahap", "Transfer Bank", "Bayar DP 50%", "Transfer Setelah Selesai"]
  cancellation_policies = [
  "Layanan dapat dibatalkan jika tidak sesuai dengan kesepakatan.",
  "Pengembalian biaya jika hasil tidak memuaskan.",
  "Revisi gratis jika layanan tidak optimal."
  ]
  area_served = ["Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Cikarang", "Karawang", "Subang", "Cikampek", "Purwakarta", "Rangkas Bitung", "Serang"]
  service_output = "Proyek pengecoran yang lebih cepat dan efisien dengan concrete pump yang andal"

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Sewa Concrete Pump Berkualitas"
  hero_description = "Kami menyediakan layanan sewa concrete pump, pompa beton, dan belalai dengan harga terjangkau, baik untuk harian maupun bulanan. Solusi pompa beton terbaik untuk proyek pengecoran Anda, didukung oleh peralatan modern dan tenaga ahli."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Harga Sewa"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Layanan jangkauan luas, gratis survey, tanpa biaya tersembunyi, operator berpengalaman, sistem pembayaran aman, buka setiap hari, konsultasi gratis, dan peralatan lengkap untuk mendukung semua proyek pengecoran Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "Concrete.bangunan.co menawarkan layanan sewa concrete pump, pompa beton, dan belalai dengan harga terjangkau. Kami mengutamakan kualitas layanan, kepuasan pelanggan, dan efisiensi proyek dengan peralatan modern serta operator berpengalaman. Pilih kami untuk mendukung kelancaran proyek pengecoran Anda dengan hasil yang optimal dan tepat waktu."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Andi|Joko|Eko|Rudi|Hendra|Agus|Wawan|Fajar|Rio}"
  message = "{Saya menyewa concrete pump dari concretepump.bangunan.co untuk proyek pengecoran rumah, dan hasilnya {sangat memuaskan|luar biasa|hebat}. Proses {berjalan lancar|dijalankan dengan baik|tertata rapi}, tepat waktu, dan kualitasnya {luar biasa|mengagumkan|terbaik}.|Concrete pump dari concretepump.bangunan.co {berhasil memenuhi|sangat mendukung|membantu suksesnya} proyek pengecoran rumah saya, dengan hasil yang {memuaskan|sesuai harapan|menakjubkan}.}"
  response = "{Terima kasih atas kepercayaannya! Kami senang dapat mendukung proyek pengecoran rumah Anda dengan {layanan terbaik|pelayanan unggulan|kualitas prima}.|Kami sangat menghargai kepercayaan Anda. Senang Anda puas dengan hasilnya! {Semoga proyek Anda terus lancar|Kami harap Anda selalu puas dengan layanan kami}.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Ayu|Sari|Fitri|Lina|Diah|Maya|Nur}"
  message = "{Concretepump.bangunan.co {sangat membantu|memudahkan|mengoptimalkan} dalam pembangunan ruko saya. Layanan mereka {profesional|handal|kompeten}, dan hasil akhirnya {sesuai|tepat|memenuhi ekspektasi} dengan yang saya inginkan.|Saya sangat terbantu dengan layanan dari concretepump.bangunan.co dalam pembangunan ruko saya. Tim mereka {profesional|berpengalaman|terlatih} dan hasilnya {memuaskan|seperti yang saya harapkan|optimal}.}"
  response = "{Kami sangat menghargai ulasan Anda. Senang mendengar bahwa Anda puas dengan layanan kami dalam {pembangunan|pengembangan|konstruksi} ruko Anda.|Terima kasih atas kepercayaan Anda. Kami senang bisa membantu mewujudkan ruko impian Anda. {Semoga usaha Anda sukses|Kami siap membantu lagi di proyek berikutnya}.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Agus|Bayu|Galih|Rizal|Bambang|Faisal|Ali|Toni|Deni}"
  message = "{Layanan concrete pump dari concretepump.bangunan.co {sangat memuaskan|luar biasa|mengesankan} untuk proyek cor kantor saya. Timnya {cepat tanggap|reaktif|sigap} dan pekerjaannya {rapi|teratur|presisi}.|Concrete pump dari concretepump.bangunan.co memberikan {hasil yang baik|layanan yang memuaskan|solusi yang tepat} untuk kantor saya. Timnya {cepat tanggap|sigap|responnya cepat} dan pekerjaannya {bersih|teratur|terorganisir}.}"
  response = "{Terima kasih! Kami berkomitmen untuk memberikan layanan terbaik bagi setiap proyek, termasuk {kantor|proyek|ruang kerja} Anda.|Kami senang dapat memberikan layanan berkualitas untuk proyek Anda. Terima kasih atas kepercayaannya! {Semoga proyek Anda sukses|Kami siap untuk proyek Anda berikutnya}.}"
  rating = 4.5

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Eko|Deni|Hendra|Toni|Wawan|Gilang|Ari|Benny|Yudi}"
  message = "{Saya {sangat puas|senang|gembira} dengan layanan sewa concrete pump dari concretepump.bangunan.co. Prosesnya {efisien|mudah|terkoordinasi dengan baik} dan hasilnya {sangat memuaskan|hebat|luar biasa}.|Layanan sewa concrete pump dari concretepump.bangunan.co {berjalan dengan lancar|efisien|tanpa hambatan} dan hasilnya {luar biasa|memuaskan|optimal}.}"
  response = "{Senang mendengar Anda puas dengan hasilnya. Terima kasih atas kepercayaannya dalam menggunakan layanan kami! {Semoga proyek berikutnya berjalan lancar|Kami harap Anda kembali lagi}.|Kami sangat menghargai kepercayaan Anda. Terima kasih telah memilih concrete pump kami untuk proyek Anda! {Kami siap membantu proyek Anda berikutnya|Sampai jumpa di proyek berikutnya}.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Lina|Dewi|Ayu|Sari|Fitri|Maya|Nur|Diah}"
  message = "{Pelayanan concretepump.bangunan.co {sangat membantu|memudahkan|mempercepat} untuk proyek cor lantai kantor saya. Solusi yang diberikan {sangat tepat|efisien|akurat} dan {efektif|bermanfaat|bernilai tambah}.|Concretepump.bangunan.co {memberikan solusi yang tepat|sangat membantu|menyediakan layanan unggulan} dalam proyek cor lantai kantor saya. Layanannya {efisien|profesional|kompeten} dan hasilnya {memuaskan|hebat|mengagumkan}.}"
  response = "{Terima kasih! Kami senang dapat membantu mewujudkan proyek cor lantai kantor Anda dengan solusi {terbaik|efisien|unggulan}.|Kami sangat menghargai ulasan Anda. Terima kasih telah memilih layanan kami! {Kami siap membantu di proyek berikutnya|Semoga hasilnya selalu memuaskan}.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Rio|Galih|Faisal|Yanto|Benny|Toni|Deni|Rizal|Wawan}"
  message = "{Saya menyewa concrete pump untuk renovasi rumah, dan hasilnya {sesuai dengan harapan|memuaskan|menakjubkan}. Layanan yang diberikan concretepump.bangunan.co {sangat profesional|berkualitas|kompeten}.|Concrete pump dari concretepump.bangunan.co {berhasil memenuhi harapan|sangat mendukung|membantu} proyek pengecoran rumah saya. Layanannya {profesional|berpengalaman|terpercaya} dan {tepat waktu|efisien|terorganisir}.}"
  response = "{Kami senang mendengar bahwa Anda puas dengan layanan kami. Terima kasih atas {ulasannya|kepercayaannya|pengakuannya}!|Terima kasih telah memilih concrete pump kami untuk renovasi rumah Anda. Kami senang layanan kami sesuai dengan harapan Anda. {Semoga proyek berikutnya sukses|Kami siap mendukung proyek lainnya}.}"
  rating = 4

[[params.tabelItems]]
  name = "Sewa Concrete Pump Mini"
  price = "3.500.000 /hari"
[[params.tabelItems]]
  name = "Sewa Concrete Pump Super Long"
  price = "25.000.000 /hari"
[[params.tabelItems]]
  name = "Sewa Concrete Pump Master Long"
  price = "35.000.000 /hari"
[[params.tabelItems]]
  name = "Sewa Concrete Pump Standar"
  price = "3.800.000 /hari"
[[params.tabelItems]]
  name = "Sewa Concrete Pump Long Boom"
  price = "7.500.000 /hari"

[params.appliList]
  "Sewa Concrete Pump Mini" = "proyek pengecoran di area sempit atau akses terbatas"
  "Sewa Concrete Pump Super Long" = "proyek pengecoran besar dengan jarak pengecoran jauh"
  "Sewa Concrete Pump Master Long" = "proyek dengan volume pengecoran besar dan jarak panjang"
  "Sewa Concrete Pump Standar" = "proyek pengecoran skala kecil hingga menengah"
  "Sewa Concrete Pump Long Boom" = "proyek dengan bangunan tinggi atau area sulit dijangkau"

[params.kegunaanList]
  "Sewa Concrete Pump Mini" = "untuk pengecoran di area yang sulit diakses atau terbatas"
  "Sewa Concrete Pump Super Long" = "memungkinkan pengecoran pada proyek dengan jarak jauh"
  "Sewa Concrete Pump Master Long" = "efisien untuk proyek skala besar dengan volume pengecoran yang banyak"
  "Sewa Concrete Pump Standar" = "solusi ideal untuk proyek pengecoran harian skala kecil hingga menengah"
  "Sewa Concrete Pump Long Boom" = "digunakan pada bangunan tinggi atau lokasi yang sulit dijangkau"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Sewa Concrete Pump (Belalai Cor) Harian & Bulanan | "
   highlight = "Concrete.bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"